### ISSUE TITLE
App lags (and sometimes crashes) on Route from Timeline to Artice screen

### ISSUE THREAD

**Issue by optimygmbh** [2d-inc/HistoryOfEverything#60]
Hi!

I think I found a bug in the app.

You can reproduce it as follow:

1. Start app (I'm using iPhone Xr ios emulator)
2. Go to "Animals" and find "Mammals"
3. Zoom the "Mammals" so that Year 210M is at top and 186 M at bottom of screen. (Mammals in the middle)
4. Click on Tap on Mammals

This route to article page is veery laggy and sometimes even the whole app crashes without any messages in the console. (You can see it here: [bug video on WeTransfer](https://we.tl/t-7owpHF8Icb))

**Comment by luigi-rosso** [comment]
The app is very graphically intense. I strongly recommend you test on a device instead of the simulator if you're looking to test performance. You should also run in profile or release mode to get a real sense of runtime performance.

You can also experiment with other simulators (the iPhone 8 simulator usually has better performance on my machine) or even Android emulators which sometimes make better use of your machine's GPU.
